apiVersion: v1
kind: Service
metadata:
  name: xm-recommendation-service
spec:
  selector:
    app: xm-recommendation-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer